# [Molecular Biology (Splice-junction Gene Sequences) Dataset](https://archive.ics.uci.edu/dataset/69/molecular+biology+splice+junction+gene+sequences)

Splice junctions are points on a DNA sequence at which `superfluous' DNA is removed during the process of protein creation in higher organisms.  The problem posed in this dataset is to recognize, given a sequence of DNA, the boundaries between exons (the parts of the DNA sequence retained after splicing) and introns (the parts of the DNA sequence that are spliced out). This problem consists of two subtasks: recognizing exon/intron boundaries (referred to as EI sites), and recognizing intron/exon boundaries (IE sites). (In the biological community, IE borders are referred to a "acceptors" while EI borders are referred to as "donors".)

### Estrutura do dataset

| Alvo  | Valores |
| ------------- | ------------- |
|class| {n, ei, ie}|

| Features  | Valores |
| ------------- | ------------- |
|Base1| {C, A, G, T, D, }| 
|Base2| {C, G, A, T, D, }| 
|Base3| {A, G, T, C, }| 
|Base4| {G, C, A, T, }| 
|Base5| {C, T, A, G, }| 
|Base6| {T, C, G, A, }| 
|Base7| {G, A, C, T, }| 
|Base8| {C, A, G, T, }| 
|Base9| {A, C, G, T, }| 
|Base10| {T, G, C, A, }| 
|Base11| {C, G, A, T, }| 
|Base12| {A, G, C, T, }| 
|Base13| {C, A, G, T, }| 
|Base14| {A, G, T, C, N, }| 
|Base15| {G, C, T, A, }| 
|Base16| {G, C, T, A, }| 
|Base17| {A, G, T, C, }| 
|Base18| {G, T, A, C, }| 
|Base19| {G, A, C, T, N, }| 
|Base20| {C, G, A, T, N, }| 
|Base21| {C, G, T, A, N, }| 
|Base22| {A, C, T, G, N, }| 
|Base23| {G, C, A, T, N, }| 
|Base24| {C, G, A, T, N, }| 
|Base25| {G, T, A, C, N, }| 
|Base26| {A, G, C, T, N, }| 
|Base27| {G, C, T, A, N, }| 
|Base28| {C, A, G, T, N, }| 
|Base29| {A, G, C, T, N, }| 
|Base30| {G, C, A, T, N, }| 
|Base31| {G, N, C, T, A, }| 
|Base32| {T, N, C, G, A, }| 
|Base33| {C, G, A, N, T, }| 
|Base34| {T, A, C, G, N, }| 
|Base35| {G, T, A, C, N, R, }| 
|Base36| {T, C, A, G, N, S, }| 
|Base37| {T, C, A, G, N, }| 
|Base38| {C, G, T, A, N, }| 
|Base39| {C, G, T, A, N, }| 
|Base40| {A, G, C, T, N, }| 
|Base41| {A, C, G, T, N, }| 
|Base42| {G, C, A, T, N, }| 
|Base43| {G, A, C, T, N, }| 
|Base44| {G, C, T, A, N, }| 
|Base45| {C, T, A, G, N, }| 
|Base46| {C, G, T, A, N, }| 
|Base47| {T, C, G, A, N, }| 
|Base48| {T, G, C, A, N, }| 
|Base49| {C, G, T, A, N, }| 
|Base50| {G, C, A, T, N, }| 
|Base51| {A, G, C, T, N, }| 
|Base52| {G, T, A, C, N, }| 
|Base53| {C, G, T, A, N, }| 
|Base54| {C, G, T, A, N, }| 
|Base55| {A, C, G, T, N, }| 
|Base56| {G, C, T, A, N, }| 
|Base57| {T, C, G, A, N, }| 
|Base58| {C, A, G, T, N, }| 
|Base59| {T, G, C, A, N, }| 
|Base60| {G, C, T, A, N, }| 

### Instalação das dependências

In [1]:
# !pip install ucimlrepo
# !pip install tensorflow
# !pip install sklearn
# !pip install pandas

In [2]:
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Flatten, Dense

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import LabelEncoder

from ucimlrepo import fetch_ucirepo 

### Importando o dataset

In [3]:
# fetch dataset 
dataset = fetch_ucirepo(id=69) 
  
# data (as pandas dataframes) 
X = dataset.data.features 
Y = dataset.data.targets 

# Transform labels to int
labels = Y["class"].unique()
for i in range(len(labels)):
  Y.loc[Y['class']==labels[i], 'class'] = i


C:\Users\AMD RYZEN\AppData\Local\Temp\ipykernel_14584\3723574641.py:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Y.loc[Y['class']==labels[i], 'class'] = i


In [4]:
for feature in X:
    uniques = X[feature].unique()
    temp = ""
    for x in uniques:
        temp += x + ", "

    print(f"|{feature}| {{{temp}}}| ")

|Base1| {C, A, G, T, D, }| 
|Base2| {C, G, A, T, D, }| 
|Base3| {A, G, T, C, }| 
|Base4| {G, C, A, T, }| 
|Base5| {C, T, A, G, }| 
|Base6| {T, C, G, A, }| 
|Base7| {G, A, C, T, }| 
|Base8| {C, A, G, T, }| 
|Base9| {A, C, G, T, }| 
|Base10| {T, G, C, A, }| 
|Base11| {C, G, A, T, }| 
|Base12| {A, G, C, T, }| 
|Base13| {C, A, G, T, }| 
|Base14| {A, G, T, C, N, }| 
|Base15| {G, C, T, A, }| 
|Base16| {G, C, T, A, }| 
|Base17| {A, G, T, C, }| 
|Base18| {G, T, A, C, }| 
|Base19| {G, A, C, T, N, }| 
|Base20| {C, G, A, T, N, }| 
|Base21| {C, G, T, A, N, }| 
|Base22| {A, C, T, G, N, }| 
|Base23| {G, C, A, T, N, }| 
|Base24| {C, G, A, T, N, }| 
|Base25| {G, T, A, C, N, }| 
|Base26| {A, G, C, T, N, }| 
|Base27| {G, C, T, A, N, }| 
|Base28| {C, A, G, T, N, }| 
|Base29| {A, G, C, T, N, }| 
|Base30| {G, C, A, T, N, }| 
|Base31| {G, N, C, T, A, }| 
|Base32| {T, N, C, G, A, }| 
|Base33| {C, G, A, N, T, }| 
|Base34| {T, A, C, G, N, }| 
|Base35| {G, T, A, C, N, R, }| 
|Base36| {T, C, A, G, N, S, }| 
|Bas

### One-hot Encoding das features

In [5]:
cat_fatures = []
for feature in dataset.data.features:
    #print(feature)
    feature_info = dataset.variables.loc[dataset.variables["name"] == feature]
    if feature_info.type.values[0] == "Categorical":
        cat_fatures.append(feature)


In [6]:
X = pd.get_dummies(X,columns=cat_fatures, dtype=int)

### Dividindo os conjuntos de teste e treino

In [7]:
x_train, x_test, y_train, y_test = train_test_split(X, Y,test_size= 0.7, random_state = 28)

### One-Hot Enconding dos Targets

In [8]:
y_train = to_categorical(y_train) 
y_true = list(y_test['class'])
y_test = to_categorical(y_test) 

### Perceptron

In [9]:
model = tf.keras.Sequential([
    Flatten(input_shape=(len(X.columns),)),
    Dense(64, activation='relu'),
    Dense(128, activation='relu'),
    Dense(len(y_train[0]), activation='softmax')
])

In [10]:
model.compile(
  loss='categorical_crossentropy', 
  optimizer='sgd', 
  metrics=['Accuracy', 'Precision', 'Recall', 'F1Score']
)
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 287)               0         
                                                                 
 dense (Dense)               (None, 64)                18432     
                                                                 
 dense_1 (Dense)             (None, 128)               8320      
                                                                 
 dense_2 (Dense)             (None, 3)                 387       
                                                                 
Total params: 27139 (106.01 KB)
Trainable params: 27139 (106.01 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### Treinamento

In [11]:
model.fit(x_train, y_train, epochs=300, batch_size=32, verbose=1)
model.evaluate(x_test,  y_test, verbose=2)

Epoch 1/300
30/30 [==============================] - 1s 1ms/step - loss: 1.0481 - Accuracy: 0.4963 - precision: 0.5129 - recall: 0.1243 - f1_score: 0.2805
Epoch 2/300
30/30 [==============================] - 0s 1ms/step - loss: 1.0050 - Accuracy: 0.5329 - precision: 0.6152 - recall: 0.2456 - f1_score: 0.2688
Epoch 3/300
30/30 [==============================] - 0s 1ms/step - loss: 0.9737 - Accuracy: 0.5340 - precision: 0.6271 - recall: 0.3584 - f1_score: 0.2493
Epoch 4/300
30/30 [==============================] - 0s 1ms/step - loss: 0.9431 - Accuracy: 0.5392 - precision: 0.6689 - recall: 0.4180 - f1_score: 0.2614
Epoch 5/300
30/30 [==============================] - 0s 1ms/step - loss: 0.9099 - Accuracy: 0.5601 - precision: 0.7168 - recall: 0.4180 - f1_score: 0.3229
Epoch 6/300
30/30 [==============================] - 0s 1ms/step - loss: 0.8735 - Accuracy: 0.5841 - precision: 0.7414 - recall: 0.4493 - f1_score: 0.3815
Epoch 7/300
30/30 [==============================] - 0s 1ms/step - los

[0.2350231260061264,
 0.9350649118423462,
 0.9362943172454834,
 0.9346171021461487,
 array([0.92633516, 0.9063063 , 0.953304  ], dtype=float32)]

In [12]:
predictions = model.predict(x_test)
print(predictions)
predictions = [list(p).index(max(p)) for p in predictions]


70/70 [==============================] - 0s 739us/step
[[7.2918629e-11 5.9472336e-06 9.9999404e-01]
 [4.4462734e-08 9.9948251e-01 5.1741744e-04]
 [9.9999964e-01 1.0447661e-10 3.2051369e-07]
 ...
 [3.9703103e-08 9.9949586e-01 5.0415570e-04]
 [2.2822092e-06 9.9979335e-01 2.0434758e-04]
 [2.4338550e-12 1.6432824e-09 1.0000000e+00]]


In [13]:
print(f'Acurácia obtida: {accuracy_score(y_true, predictions) * 100:.2f}%')
print(f'Precisão obtida: {precision_score(y_true, predictions, average="macro") * 100:.2f}%')
print(f'Recall obtido: {recall_score(y_true, predictions, average="macro") * 100:.2f}%')
print(f'F1 Score obtida: {f1_score(y_true, predictions, average="macro") * 100:.2f}%')


Acurácia obtida: 93.51%
Precisão obtida: 92.56%
Recall obtido: 93.23%
F1 Score obtida: 92.86%
