# [Molecular Biology (Splice-junction Gene Sequences) Dataset](https://archive.ics.uci.edu/dataset/69/molecular+biology+splice+junction+gene+sequences)

Splice junctions are points on a DNA sequence at which `superfluous' DNA is removed during the process of protein creation in higher organisms.  The problem posed in this dataset is to recognize, given a sequence of DNA, the boundaries between exons (the parts of the DNA sequence retained after splicing) and introns (the parts of the DNA sequence that are spliced out). This problem consists of two subtasks: recognizing exon/intron boundaries (referred to as EI sites), and recognizing intron/exon boundaries (IE sites). (In the biological community, IE borders are referred to a "acceptors" while EI borders are referred to as "donors".)

### Estrutura do dataset

| Alvo  | Valores |
| ------------- | ------------- |
|class| {n, ei, ie}|

| Features  | Valores |
| ------------- | ------------- |
|Base1| {C, A, G, T, D, }| 
|Base2| {C, G, A, T, D, }| 
|Base3| {A, G, T, C, }| 
|Base4| {G, C, A, T, }| 
|Base5| {C, T, A, G, }| 
|Base6| {T, C, G, A, }| 
|Base7| {G, A, C, T, }| 
|Base8| {C, A, G, T, }| 
|Base9| {A, C, G, T, }| 
|Base10| {T, G, C, A, }| 
|Base11| {C, G, A, T, }| 
|Base12| {A, G, C, T, }| 
|Base13| {C, A, G, T, }| 
|Base14| {A, G, T, C, N, }| 
|Base15| {G, C, T, A, }| 
|Base16| {G, C, T, A, }| 
|Base17| {A, G, T, C, }| 
|Base18| {G, T, A, C, }| 
|Base19| {G, A, C, T, N, }| 
|Base20| {C, G, A, T, N, }| 
|Base21| {C, G, T, A, N, }| 
|Base22| {A, C, T, G, N, }| 
|Base23| {G, C, A, T, N, }| 
|Base24| {C, G, A, T, N, }| 
|Base25| {G, T, A, C, N, }| 
|Base26| {A, G, C, T, N, }| 
|Base27| {G, C, T, A, N, }| 
|Base28| {C, A, G, T, N, }| 
|Base29| {A, G, C, T, N, }| 
|Base30| {G, C, A, T, N, }| 
|Base31| {G, N, C, T, A, }| 
|Base32| {T, N, C, G, A, }| 
|Base33| {C, G, A, N, T, }| 
|Base34| {T, A, C, G, N, }| 
|Base35| {G, T, A, C, N, R, }| 
|Base36| {T, C, A, G, N, S, }| 
|Base37| {T, C, A, G, N, }| 
|Base38| {C, G, T, A, N, }| 
|Base39| {C, G, T, A, N, }| 
|Base40| {A, G, C, T, N, }| 
|Base41| {A, C, G, T, N, }| 
|Base42| {G, C, A, T, N, }| 
|Base43| {G, A, C, T, N, }| 
|Base44| {G, C, T, A, N, }| 
|Base45| {C, T, A, G, N, }| 
|Base46| {C, G, T, A, N, }| 
|Base47| {T, C, G, A, N, }| 
|Base48| {T, G, C, A, N, }| 
|Base49| {C, G, T, A, N, }| 
|Base50| {G, C, A, T, N, }| 
|Base51| {A, G, C, T, N, }| 
|Base52| {G, T, A, C, N, }| 
|Base53| {C, G, T, A, N, }| 
|Base54| {C, G, T, A, N, }| 
|Base55| {A, C, G, T, N, }| 
|Base56| {G, C, T, A, N, }| 
|Base57| {T, C, G, A, N, }| 
|Base58| {C, A, G, T, N, }| 
|Base59| {T, G, C, A, N, }| 
|Base60| {G, C, T, A, N, }| 

### Instalação das dependências

In [14]:
# !pip install ucimlrepo
# !pip install tensorflow
# !pip install sklearn
# !pip install pandas

In [15]:
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Flatten, Dense

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import LabelEncoder

from ucimlrepo import fetch_ucirepo 
pd.options.mode.copy_on_write = True

### Importando o dataset

In [16]:
# fetch dataset 
dataset = fetch_ucirepo(id=69) 
  
# data (as pandas dataframes) 
X = dataset.data.features 
Y = dataset.data.targets 

# Transform labels to int
labels = Y["class"].unique()
for i in range(len(labels)):
  Y.loc[Y['class']==labels[i], 'class'] = i


In [17]:
for feature in X:
    uniques = X[feature].unique()
    temp = ""
    for x in uniques:
        temp += x + ", "

    print(f"|{feature}| {{{temp}}}| ")

|Base1| {C, A, G, T, D, }| 
|Base2| {C, G, A, T, D, }| 
|Base3| {A, G, T, C, }| 
|Base4| {G, C, A, T, }| 
|Base5| {C, T, A, G, }| 
|Base6| {T, C, G, A, }| 
|Base7| {G, A, C, T, }| 
|Base8| {C, A, G, T, }| 
|Base9| {A, C, G, T, }| 
|Base10| {T, G, C, A, }| 
|Base11| {C, G, A, T, }| 
|Base12| {A, G, C, T, }| 
|Base13| {C, A, G, T, }| 
|Base14| {A, G, T, C, N, }| 
|Base15| {G, C, T, A, }| 
|Base16| {G, C, T, A, }| 
|Base17| {A, G, T, C, }| 
|Base18| {G, T, A, C, }| 
|Base19| {G, A, C, T, N, }| 
|Base20| {C, G, A, T, N, }| 
|Base21| {C, G, T, A, N, }| 
|Base22| {A, C, T, G, N, }| 
|Base23| {G, C, A, T, N, }| 
|Base24| {C, G, A, T, N, }| 
|Base25| {G, T, A, C, N, }| 
|Base26| {A, G, C, T, N, }| 
|Base27| {G, C, T, A, N, }| 
|Base28| {C, A, G, T, N, }| 
|Base29| {A, G, C, T, N, }| 
|Base30| {G, C, A, T, N, }| 
|Base31| {G, N, C, T, A, }| 
|Base32| {T, N, C, G, A, }| 
|Base33| {C, G, A, N, T, }| 
|Base34| {T, A, C, G, N, }| 
|Base35| {G, T, A, C, N, R, }| 
|Base36| {T, C, A, G, N, S, }| 
|Bas

### One-hot Encoding das features

In [18]:
cat_fatures = []
for feature in dataset.data.features:
    #print(feature)
    feature_info = dataset.variables.loc[dataset.variables["name"] == feature]
    if feature_info.type.values[0] == "Categorical":
        cat_fatures.append(feature)


In [19]:
X = pd.get_dummies(X,columns=cat_fatures, dtype=int)

### Dividindo os conjuntos de teste e treino

In [20]:
x_train, x_test, y_train, y_test = train_test_split(X, Y,test_size= 0.3, random_state = 28)

### One-Hot Enconding dos Targets

In [21]:
y_train = to_categorical(y_train) 
y_true = list(y_test['class'])
y_test = to_categorical(y_test) 

### Perceptron

In [22]:
model = tf.keras.Sequential([
    Flatten(input_shape=(len(X.columns),)),
    Dense(64, activation='relu'),
    Dense(128, activation='relu'),
    Dense(len(y_train[0]), activation='softmax')
])

In [23]:
model.compile(
  loss='categorical_crossentropy', 
  optimizer='sgd', 
  metrics=['Accuracy', 'Precision', 'Recall', 'F1Score']
)
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 287)               0         
                                                                 
 dense_3 (Dense)             (None, 64)                18432     
                                                                 
 dense_4 (Dense)             (None, 128)               8320      
                                                                 
 dense_5 (Dense)             (None, 3)                 387       
                                                                 
Total params: 27139 (106.01 KB)
Trainable params: 27139 (106.01 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### Treinamento

In [24]:
model.fit(x_train, y_train, epochs=300, batch_size=32, verbose=1)
model.evaluate(x_test,  y_test, verbose=2)

Epoch 1/300
70/70 [==============================] - 1s 971us/step - loss: 1.0177 - Accuracy: 0.4908 - precision: 0.6519 - recall: 0.1652 - f1_score: 0.3416
Epoch 2/300
70/70 [==============================] - 0s 942us/step - loss: 0.9082 - Accuracy: 0.5687 - precision: 0.7182 - recall: 0.3560 - f1_score: 0.3946
Epoch 3/300
70/70 [==============================] - 0s 957us/step - loss: 0.7944 - Accuracy: 0.6785 - precision: 0.8115 - recall: 0.4357 - f1_score: 0.5958
Epoch 4/300
70/70 [==============================] - 0s 928us/step - loss: 0.6552 - Accuracy: 0.7797 - precision: 0.8765 - recall: 0.5911 - f1_score: 0.7429
Epoch 5/300
70/70 [==============================] - 0s 942us/step - loss: 0.5105 - Accuracy: 0.8580 - precision: 0.9194 - recall: 0.7510 - f1_score: 0.8401
Epoch 6/300
70/70 [==============================] - 0s 957us/step - loss: 0.3922 - Accuracy: 0.8979 - precision: 0.9354 - recall: 0.8433 - f1_score: 0.8866
Epoch 7/300
70/70 [==============================] - 0s 94

[0.2822315990924835,
 0.9352142214775085,
 0.9361924529075623,
 0.9352142214775085,
 array([0.9356223, 0.8993289, 0.9510489], dtype=float32)]

In [25]:
predictions = model.predict(x_test)
print(predictions)
predictions = [list(p).index(max(p)) for p in predictions]


30/30 [==============================] - 0s 690us/step
[[7.51154645e-14 4.89042918e-07 9.99999523e-01]
 [1.86341165e-09 9.99999881e-01 1.14766316e-07]
 [9.99997616e-01 3.74705624e-14 2.35933680e-06]
 ...
 [6.86284432e-11 1.28002069e-03 9.98720050e-01]
 [8.36516047e-05 5.41557732e-08 9.99916315e-01]
 [8.81679105e-12 9.99982595e-01 1.73448861e-05]]


In [26]:
print(f'Acurácia obtida: {accuracy_score(y_true, predictions) * 100:.2f}%')
print(f'Precisão obtida: {precision_score(y_true, predictions, average="macro") * 100:.2f}%')
print(f'Recall obtido: {recall_score(y_true, predictions, average="macro") * 100:.2f}%')
print(f'F1 Score obtida: {f1_score(y_true, predictions, average="macro") * 100:.2f}%')


Acurácia obtida: 93.52%
Precisão obtida: 92.43%
Recall obtido: 93.35%
F1 Score obtida: 92.87%
